"""
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

febonacci = [1, 2]
feb_even = []

while febonacci[-1] < 4000000:
    f = febonacci[-1] + febonacci[-2]
    febonacci.append(f)
    if f % 2 == 0:
        feb_even.append(f)

print(sum(feb_even))
