# -*- coding: utf-8 -*-
"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

pentagonal = []

for e in range(1,5000):
    e = e*(3*e-1)/2
    pentagonal.append(e)

D_l = []

n = 0
for j in pentagonal:
    for k in pentagonal[0:n]:
        if j + k in pentagonal and j - k in pentagonal:
            D_l.append(abs(k-j))
    if len(D_l) > 0:
        print(D_l)
        break
    print(j)
    n += 1

print(min(D_l))
